### PR TITLE
Fix logging context propagation

### LINKED ISSUE #180: [Java] Ensure Restate context attributes are applied to handler-emitted log4j log entries
With the removal of `GrpcContextDataProvider` in https://github.com/restatedev/sdk-java/pull/179 we no longer preserve the Restate operation name and invocation id into customer calls across threads in Java, though this still works for Kotlin code. We made this tradeoff to fix a different issue in AWS Lambda, that was related to the custom context provider.

Objective: restore the functionality where handler-logged entries are properly annotated with Restate context.

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #180

The GrpcContextDataProvider was not wrong on itself, the problem was that we have to merge SPI files when creating the shadowJar. See https://github.com/apache/logging-log4j2/issues/2099

### CODE REVIEW

File: sdk-core/src/main/java/dev/restate/sdk/core/ExecutorSwitchingWrappers.java [hunk 1]
```diff
@@ -48,8 +47,8 @@ private ExecutorSwitchingServerCallListener(
     }
 
     @Override
-    public void onMessageAndHalfClose(MessageLite message) {
-      userExecutor.execute(() -> listener.onMessageAndHalfClose(message));
+    public void invoke(MessageLite message) {
+      userExecutor.execute(() -> listener.invoke(message));
     }
 
     // A bit of explanation why the following methods are not executed on the user executor.
```
Comment (pcholakov) [inline sdk-core/src/main/java/dev/restate/sdk/core/ExecutorSwitchingWrappers.java:54]: Nit: we've renamed the methods onReady/onCancel/onComplete

File: sdk-core/src/main/java/dev/restate/sdk/core/InvocationStateMachine.java [hunk 2]
```diff
@@ -735,7 +743,7 @@ public String toString() {
         + serviceName
         + '\''
         + ", state="
```
Comment (pcholakov) [inline sdk-core/src/main/java/dev/restate/sdk/core/InvocationStateMachine.java:745]: Nit: maybe rename the string rendering to match the field name:
```suggestion
        + ", invocationState="
```

File: sdk-core/src/test/resources/log4j2.properties [hunk 3]
```diff
@@ -5,4 +5,4 @@ appender.testlogger.name = TestLogger
 appender.testlogger.type = CONSOLE
 appender.testlogger.target = SYSTEM_ERR
 appender.testlogger.layout.type = PatternLayout
-appender.testlogger.layout.pattern = %-4r %-5p %notEmpty{[%X{restateServiceMethod}]}%notEmpty{[%X{restateInvocationId}]} [%t] %c - %m%n
\ No newline at end of file
+appender.testlogger.layout.pattern = %-4r %-5p %X [%t] %c:%L - %m%n
```
Comment (pcholakov) [inline sdk-core/src/test/resources/log4j2.properties:8]: 👍

**Review by pcholakov — APPROVED** [review]
Thanks for figuring this one out!
